name: Build and Release Windows Executable

on:
  push:
    tags:
      - "v*.*.*"  # バージョンタグのみに対してトリガー
    workflow_dispatch:  # 手動実行のトリガー

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python環境のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy pandas customtkinter Pillow pyinstaller pyinstaller_versionfile chardet
          pip install git+https://github.com/Kotetsu0000/book_search_api.git

      - name: バージョンファイルを生成
        run: create-version-file version.yaml --outfile version_info.txt

      - name: PyInstallerで実行ファイルを生成
        run: |
          pyinstaller EasyBookManager.py --noconsole --icon=images/favicon.ico --add-data "images/*:./images/" --version-file version_info.txt --clean

      - name: Artifactsをアップロード
        uses: actions/upload-artifact@v4
        with:
          name: EasyBookManager
          path: ./dist/EasyBookManager

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Artifactsをダウンロード
        uses: actions/download-artifact@v4
        with:
          name: EasyBookManager

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            EasyBookManager
          draft: false
          prerelease: false

      - name: Zip Artifacts
        run: |
          zip -r EasyBookManager.zip EasyBookManager

      - name: Append Binaly
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./EasyBookManager.zip
          asset_name: EasyBookManager.zip
          asset_content_type: application/zip
